CREATE TABLE municipality (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(64) NOT NULL,
    municipality_id BIGINT REFERENCES municipality (id),
    reports_to_user_id BIGINT REFERENCES app_user (id)
);

CREATE TABLE market (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipality_id BIGINT NOT NULL REFERENCES municipality (id),
    name VARCHAR(255) NOT NULL,
    city VARCHAR(128) NOT NULL,
    district VARCHAR(128) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    opening_days VARCHAR(128) NOT NULL,
    hours VARCHAR(64) NOT NULL,
    vendor_count INT NOT NULL DEFAULT 0,
    type VARCHAR(64),
    address VARCHAR(512),
    image VARCHAR(512)
);

CREATE TABLE vendor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id BIGINT NOT NULL REFERENCES market (id),
    name VARCHAR(255) NOT NULL,
    stall_code VARCHAR(64),
    score INT NOT NULL DEFAULT 70,
    app_user_id BIGINT REFERENCES app_user (id)
);

ALTER TABLE app_user ADD COLUMN vendor_id BIGINT REFERENCES vendor (id);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    abbr VARCHAR(16),
    category VARCHAR(64),
    unit VARCHAR(64),
    subtypes_json VARCHAR(4000)
);

CREATE TABLE market_schema_cell (
    market_id BIGINT NOT NULL REFERENCES market (id),
    cell_id VARCHAR(32) NOT NULL,
    cell_type VARCHAR(32) NOT NULL,
    stall_code VARCHAR(64),
    vendor_id BIGINT REFERENCES vendor (id),
    PRIMARY KEY (market_id, cell_id)
);

CREATE TABLE vendor_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT NOT NULL REFERENCES vendor (id),
    product_id BIGINT NOT NULL REFERENCES product (id),
    unit_price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'TRY',
    published BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (vendor_id, product_id)
);

CREATE TABLE price_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id BIGINT NOT NULL REFERENCES market (id),
    vendor_id BIGINT REFERENCES vendor (id),
    product_id BIGINT NOT NULL REFERENCES product (id),
    price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'TRY',
    confidence INT,
    source VARCHAR(64),
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE complaint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id BIGINT NOT NULL REFERENCES market (id),
    description VARCHAR(2000),
    status VARCHAR(32) NOT NULL DEFAULT 'NEW',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    evidence_object_key VARCHAR(512),
    citizen_session_id VARCHAR(128),
    assigned_officer_id BIGINT REFERENCES app_user (id),
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inspection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id BIGINT NOT NULL REFERENCES market (id),
    officer_user_id BIGINT NOT NULL REFERENCES app_user (id),
    inspection_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    violations_count INT NOT NULL DEFAULT 0,
    notes VARCHAR(2000)
);

CREATE TABLE violation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id BIGINT REFERENCES inspection (id),
    vendor_id BIGINT REFERENCES vendor (id),
    violation_type VARCHAR(128) NOT NULL,
    description VARCHAR(2000)
);

CREATE TABLE invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT NOT NULL REFERENCES vendor (id),
    market_id BIGINT NOT NULL REFERENCES market (id),
    object_key VARCHAR(512) NOT NULL,
    checksum VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'UPLOADED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoice (id),
    product_id BIGINT REFERENCES product (id),
    quantity NUMERIC(12, 3),
    unit VARCHAR(64),
    unit_price NUMERIC(12, 2),
    line_total NUMERIC(12, 2),
    raw_label VARCHAR(512)
);

CREATE TABLE ocr_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoice (id),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    raw_output_json VARCHAR(8000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(255),
    action VARCHAR(128) NOT NULL,
    resource_type VARCHAR(64),
    resource_id VARCHAR(64),
    trace_id VARCHAR(64),
    payload_json VARCHAR(4000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_market_city ON market (city);
CREATE INDEX idx_vendor_market ON vendor (market_id);
CREATE INDEX idx_vendor_product_vendor ON vendor_product (vendor_id);
CREATE INDEX idx_complaint_market ON complaint (market_id);
CREATE INDEX idx_complaint_status ON complaint (status);
CREATE INDEX idx_price_obs_market_product ON price_observation (market_id, product_id);
